### ISSUE TITLE
策略里面的分支类如何受spring容器管理

### ISSUE THREAD

**Issue by laobing2019** [dsc-cmt/spring-easy-strategy#12]
以介绍里面的ChineseGirlHelloStrategy为例，如果该类里面需要大量使用spring的bean做一些业务逻辑处理，那将这个ChineseGirlHelloStrategy使用@Service丢入容器里面，会影响策略的使用吗

**Comment by shengchaojie** [comment]
不影响
ChineseGirlHelloStrategy本来就是在spring容器里的

**Comment by laobing2019** [comment]
好的，用过了，挺好用的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dsc-cmt/spring-easy-strategy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月8日(星期四) 凌晨0:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dsc-cmt/spring-easy-strategy] 策略里面的分支类如何受spring容器管理 (#12)





 
不影响
 ChineseGirlHelloStrategy本来就是在spring容器里的
